language: node_js
node_js:
- 12.14.1
install:
- npm install
- lerna bootstrap
script:
- lerna run lint --stream
- lerna run build --stream
after_script:
- lerna run test
- lerna run coveralls --scope @inkline/inkline
env:
  global:
    secure: tqtY+KktpHoArTJijk9fQIOVkPSCSExmdj5uIhUX62Wt+PB2Ta1GA31/CBwCusegAp09W7nkFkF222xyX2xsE0PbTP68gZZIxHV/7Uv/CaTr75t7u4in9pHkXbOrhgiVJV70UgzzQYHHERT/Qa3YfFLE1uLjI6mOYB2Jh6uPWxW9fF9Qq9JXkrAATo9QB0idx6lYD7GHeFki8cufvPTbllP+r1x4vtGNVohdKXpro/CJllAGDqyYiXXUMatTc51qFue5EI88O8VDLz9yjQy0Ot+Hx3QlNX5LTzGxfISIerc8doTYtRKhtbzgtp8e2jKTAN/k/y+K6JkVrZu96FOeksspPxfWTSkdGN+Q06261ZaHh4xOP8xpAaesacxYXaCRgfc4fIb+2dQdmkA0VXWlPtz5ELYohYQavAjJrd7cINSwA0YLdFOMt7n5c7Bsc1hqY+rmsUzrm4uCV8XgDyNnxD+hTpg8N/hVKKbBkAkGunrFXQQeFVSuXLU/Kowx0QaqRFJI8DNTQd53GibfxVFBYc/fTD+dZpt3Ul3V1avAgOKcY7SsfQgnmgu+7o534k4aP4lMU6vVPMOX9JP5L1zkpD/uym6aaY2f17wkziqnRlnLwtTLshQHeASeXBZ9u+s6ozPk1Yy0IYXAR3YV9Cjj2W26fG0AxqSzuOp/i40uNNI=
