name: Inkline
on: [ 'push', 'pull_request' ]
jobs:
    build:
        runs-on: ubuntu-16.04
        strategy:
            matrix:
                node: [ '12' ]
        name: Node ${{ matrix.node }}
        steps:
            -   name: Setup repository
                uses: actions/checkout@v2
            -   name: Setup node
                uses: actions/setup-node@v1
                with:
                    node-version: ${{ matrix.node }}
            -   run: npm install
            -   run: npm install -g lerna
            -   run: lerna link
            -   run: lerna run build
            -   run: lerna run lint
            -   run: lerna run test
            -   name: Coveralls
                uses: coverallsapp/github-action@master
                with:
                    path-to-lcov: packages/inkline/coverage/lcov.info
                    github-token: ${{ secrets.GITHUB_TOKEN }}
